The ``101-lazy_matrix_mul`` module
============================

Using ``lazy_matrix_mul``
---------------------

Import module:
	>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

Test Cases:
	>>> lazy_matrix_mul([[1, 2], [3, 4]], [[5, 6], [7, 8]])
    	array([[19, 22],
	       [43, 50]])

    	>>> lazy_matrix_mul([[5, 2, 3], [7, 13, 2], [1, 0, 3]], [[2, 3], [6, 9]])
    	Traceback (most recent call last):
        ...
    	ValueError: shapes (3,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

	>>> lazy_matrix_mul([], [[3]])
    	Traceback (most recent call last):
    	...
    	ValueError: shapes (0,) and (1,1) not aligned: 0 (dim 0) != 1 (dim 0)

	>>> lazy_matrix_mul([[4]], [])
    	Traceback (most recent call last):
    	...
    	ValueError: shapes (1,1) and (0,) not aligned: 1 (dim 1) != 0 (dim 0)

	>>> lazy_matrix_mul([[3]], [[9]])
    	array([[27]])

	>>> lazy_matrix_mul("foo", [[9]])
    	Traceback (most recent call last):
    	...
    	ValueError: Scalar operands are not allowed, use '*' instead

	>>> lazy_matrix_mul([[8]], "bar")
    	Traceback (most recent call last):
    	...
    	ValueError: Scalar operands are not allowed, use '*' instead

	>>> lazy_matrix_mul([1, 3, 4], [[9]])
	Traceback (most recent call last):
	...
	ValueError: shapes (3,) and (1,1) not aligned: 3 (dim 0) != 1 (dim 0)

	>>> lazy_matrix_mul([[8]], [2, 4, 6])
	Traceback (most recent call last):
	...
	ValueError: shapes (1,1) and (3,) not aligned: 1 (dim 1) != 3 (dim 0)

	>>> lazy_matrix_mul([["foo"]], [[2, 4, 6]])
	Traceback (most recent call last):
	...
	TypeError: invalid data type for einsum

	>>> lazy_matrix_mul([[2, 4, 6]], [["foo"]])
	Traceback (most recent call last):
	...
	ValueError: shapes (1,3) and (1,1) not aligned: 3 (dim 1) != 1 (dim 0)

	>>> lazy_matrix_mul([[1, 2], [3, 4, 5], [3, 4]], [[5, 6, 1], [7, 8, 2]])
	Traceback (most recent call last):
	...
	ValueError: setting an array element with a sequence.

	Test b bad rows:
	>>> lazy_matrix_mul([[4, 2], [3, 4], [3, 4]], [[3, 6, 1], [7, 2]])
	Traceback (most recent call last):
	...
	ValueError: setting an array element with a sequence.

	>>> lazy_matrix_mul([[4]])
	Traceback (most recent call last):
	...
	TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'

	>>> lazy_matrix_mul()
	Traceback (most recent call last):
	...
	TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'
